# example netlify.toml
[build]
  command = "npm run build"
  functions = "Baseball 101/netlify/functions"
  publish = "Baseball 101/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
